version: '3.8'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 49828:80
        restart: always
        depends_on:
            - php-fpm
            - db
        # networks:
        #     - localnet

    php-fpm:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - .:/var/www/html
        # networks:
        #     - localnet

    db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - 3306:3306
        environment:
#            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
#         networks:
#             - localnet

# networks:
#   localnet:
#     name: localnet
#     external: true